apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: streamsets
  name: streamsets
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: streamsets
    spec:
      containers:
      - image: trivadisbds/streamsets-kafka-nosql
        name: streamsets
        resources:
          limits:
            cpu: "1.5"
            memory: "8Gi"
          requests:
            cpu: "1"
            memory: "6Gi"
        ports:
        - containerPort: 18630
      hostname: streamsets
      restartPolicy: Always
status: {}
